# frozen_string_literal: true

require 'fileutils'
require 'erb'
require_relative '../../../spec/support/schema_loader'
require_relative 'entity_generator'

module CDEKApiClient
  module Generators
    # EndpointGenerator parses OpenAPI schemas and creates ruby API endpoint classes.
    class EndpointGenerator
      def initialize
        @api_dir = File.expand_path('../api/generated', __dir__)
      end

      def generate_all
        FileUtils.mkdir_p(@api_dir)

        schemas = SchemaLoader.load_schemas['schemas']
        endpoints_by_tag = Hash.new { |h, k| h[k] = [] }

        schemas.each do |schema_entry|
          schema = schema_entry['schema']
          next unless schema['paths']

          schema['paths'].each do |path, methods|
            methods.each do |method, details|
              next unless %w[get post put delete patch].include?(method)

              tag = (details['tags'] || ['Common']).first

              # Determine return type
              return_type = extract_return_type(details['responses'])

              endpoints_by_tag[tag] << {
                path: path,
                method: method,
                operationId: details['operationId'],
                summary: details['summary'],
                parameters: details['parameters'] || [],
                return_type: return_type
              }
            end
          end
        end

        endpoints_by_tag.each do |tag, endpoints|
          generate_endpoint_class(tag, endpoints)
        end

        puts "Generated #{endpoints_by_tag.keys.size} API endpoint classes!"
      end

      private

      def extract_return_type(responses)
        return nil unless responses

        # Look for a 200 or 202 response
        success_response = responses['200'] || responses['202']
        return nil unless success_response

        content = success_response['content']
        return nil unless content && content['application/json']

        schema = content['application/json']['schema']
        return nil unless schema

        if schema['$ref']
          ref_name = schema['$ref'].split('/').last
          mapped = EntityGenerator::MAPPING[ref_name]
          return { type: 'object', class: mapped } if mapped
        elsif schema['type'] == 'array' && schema['items'] && schema['items']['$ref']
          ref_name = schema['items']['$ref'].split('/').last
          mapped = EntityGenerator::MAPPING[ref_name]
          return { type: 'array', class: mapped } if mapped
        end

        nil
      end

      def generate_endpoint_class(tag, endpoints)
        class_name = to_camel_case(tag.gsub(/[^a-zA-Z0-9]/, ''))
        file_name = to_snake_case(class_name)
        file_path = File.join(@api_dir, "#{file_name}.rb")

        methods = endpoints.map { |ep| generate_method(ep) }.compact.uniq

        return if methods.empty?

        template = <<~ERB
          # frozen_string_literal: true

          # Auto-generated by EndpointGenerator

          module CDEKApiClient
            module API
              # <%= tag %> API endpoints
              class <%= class_name %>
                def initialize(client)
                  @client = client
                end
          #{'      '}
                <%= methods.join("\n\n      ").gsub("\n", "\n      ") %>
              end
            end
          end
        ERB

        File.write(file_path, ERB.new(template, trim_mode: '-').result(binding))
      end

      def self.method_name_for(operation_id, path, http_method)
        method_name = if operation_id && !operation_id.match?(/_\d+$/)
                        operation_id.gsub('::', '/').gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2').gsub(/([a-z\d])([A-Z])/, '\1_\2').tr('-', '_').downcase
                      else
                        clean_path = path.sub(%r{^/v2/}, '').gsub(/\{[^}]+\}/, '').gsub(%r{/+}, '_').chomp('_')
                        "#{http_method}_#{clean_path}"
                      end

        method_name = "do_#{method_name}" if %w[class return begin end do if else unless].include?(method_name)
        method_name
      end

      def generate_method(endpoint)
        path = endpoint[:path]
        http_method = endpoint[:method]
        operation_id = endpoint[:operationId]
        summary = endpoint[:summary]
        return_type = endpoint[:return_type]

        method_name = self.class.method_name_for(operation_id, path, http_method)

        path_params = path.scan(/\{([^}]+)\}/).flatten.map { |p| to_snake_case(p) }
        takes_body = %w[post put patch].include?(http_method)

        params = path_params.dup
        params << 'body_data = {}' if takes_body
        params << 'query_params = {}'
        params_str = params.empty? ? '' : "(#{params.join(', ')})"

        path_str = path.gsub(/\{([^}]+)\}/) { |_m| "\#{#{to_snake_case(::Regexp.last_match(1))}}" }
        path_str = path_str.sub(%r{^/v2/}, '')

        req_call = "@client.request('#{http_method}', \"#{path_str}\""
        req_call += ', body: body_data' if takes_body
        req_call += ', query: query_params'
        req_call += ')'

        # Build the return instantiation logic
        if path.end_with?('.pdf')
          yard_return = 'String'
          req_call.sub!(')', ', parse_response: false)')
          return_logic = <<~RUBY
            return response.body if response.is_a?(Net::HTTPSuccess)
            @client.send(:handle_response, response)
          RUBY
        elsif return_type
          yard_return = return_type[:type] == 'array' ? "Array<CDEKApiClient::Entities::#{return_type[:class]}>" : "CDEKApiClient::Entities::#{return_type[:class]}"

          return_logic = if return_type[:type] == 'array'
                           <<~RUBY
                             result = @client.send(:handle_response, response)
                             return result unless result.is_a?(Array)
                             result.map { |item| CDEKApiClient::Entities::#{return_type[:class]}.new(item) }
                           RUBY
                         else
                           <<~RUBY
                             result = @client.send(:handle_response, response)
                             return result unless result.is_a?(Hash) && !result.empty?
                             CDEKApiClient::Entities::#{return_type[:class]}.new(result)
                           RUBY
                         end
        else
          yard_return = 'Hash'
          return_logic = '      @client.send(:handle_response, response)'
        end

        <<~RUBY
          # #{summary}
          # HTTP #{http_method.upcase} #{path}
          # @return [#{yard_return}]
          def #{method_name}#{params_str}
            response = #{req_call}
            #{return_logic.strip}
          end
        RUBY
      end

      def fallback_method_name(path, method)
        clean_path = path.sub(%r{^/v2/}, '').gsub(/\{[^}]+\}/, '').gsub(%r{/+}, '_').chomp('_')
        "#{method}_#{clean_path}"
      end

      def to_camel_case(str)
        str.split('_').map(&:capitalize).join
      end

      def to_snake_case(str)
        str.gsub('::', '/')
           .gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
           .gsub(/([a-z\d])([A-Z])/, '\1_\2')
           .tr('-', '_')
           .downcase
      end
    end
  end
end
