# frozen_string_literal: true

require 'fileutils'
require_relative '../../../spec/support/schema_loader'

module CDEKApiClient
  module Generators
    # MockGenerator outputs an AutoMocker module that dynamically mocks the CDEK API
    # based on the generated OpenAPI fixtures.
    class MockGenerator
      def endpoints
        schemas = SchemaLoader.load_schemas['schemas']
        all_endpoints = []

        schemas.each do |schema_entry|
          schema = schema_entry['schema']
          next unless schema['paths']

          schema['paths'].each do |path, methods|
            methods.each do |method, details|
              next unless %w[get post put delete patch].include?(method)

              status = '200'
              status = details['responses'].keys.find { |k| k.start_with?('2') } || '200' if details['responses']

              all_endpoints << { path: path, method: method, response_status: status.to_i }
            end
          end
        end

        all_endpoints.uniq { |e| [e[:path], e[:method]] }
      end

      def generate_all
        puts 'Generating AutoMocker from OpenAPI schemas...'

        output_file = File.expand_path('../../testing/auto_mocker.rb', __dir__)
        FileUtils.mkdir_p(File.dirname(output_file))

        ruby_code = <<~RUBY
          # frozen_string_literal: true

          # Auto-generated by MockGenerator
          require 'webmock'
          require 'json'

          module CDEKApiClient
            module Testing
              module AutoMocker
                extend WebMock::API
          #{'      '}
                # Sets up WebMock stubs for every generated OpenAPI endpoint
                def self.stub_all_endpoints!(base_url: nil)
                  @base_url = base_url || ENV['CDEK_API_URL'] || 'https://api.edu.cdek.ru/v2'
          #{'        '}
                  stub_auth
        RUBY

        endpoints.each do |endpoint|
          path = endpoint[:path] # e.g. "/v2/orders/{uuid}"
          method = endpoint[:method]
          status = endpoint[:response_status]

          file_base = path.gsub('/', '_').gsub(/_{2,}/, '_').gsub(/[{}]/, '').sub(/^_/, '') + "_#{method}"
          var_name = file_base.gsub(/[^a-zA-Z0-9_]/, '_')

          # Remove the /v2/ prefix since the Client appends paths to @base_url (which already has /v2)
          path_without_v2 = path.sub(%r{^/?v2/}, '')

          # Convert params like {uuid} to a regex pattern matching any segment
          regex_str = path_without_v2.gsub(/\{[^}]+\}/, '[^/]+')

          ruby_code += <<~RUBY

              # #{method.upcase} #{path}
            fixture_path_#{var_name} = File.expand_path('fixtures/responses/#{file_base}_#{status}.json', __dir__)
            body_content = File.exist?(fixture_path_#{var_name}) ? File.read(fixture_path_#{var_name}) : '{}'
            stub_request(:#{method}, %r{\#{Regexp.escape(@base_url)}/#{regex_str}(?:\\?|$)})
              .to_return(
                status: #{status},
                body: body_content,
                headers: { 'Content-Type' => 'application/json' }
              )
          RUBY
        end

        ruby_code += <<~RUBY
                end
          #{'      '}
                def self.stub_auth
                  base_without_v2 = @base_url.sub(%r{/v2/?$}, '')
                  stub_request(:post, %r{\#{Regexp.escape(base_without_v2)}/v2/oauth/token.*})
                    .to_return(
                      status: 200,
                      body: {
                        access_token: 'mock_access_token_12345',
                        token_type: 'bearer',
                        expires_in: 3599,
                        scope: '',
                        jti: 'mock_jti_12345'
                      }.to_json,
                      headers: { 'Content-Type' => 'application/json' }
                    )
                end
              end
            end
          end
        RUBY

        File.write(output_file, ruby_code)
        puts "Generated AutoMocker: #{output_file}"
      end
    end
  end
end
