# frozen_string_literal: true

require 'fileutils'
require 'erb'
require_relative '../../../spec/support/schema_loader'
require_relative 'endpoint_generator'

module CDEKApiClient
  module Generators
    # RspecGenerator parses OpenAPI schemas and generates automated contract specs
    # for every generated endpoint, completely asserting that parsing works against the auto mock.
    class RspecGenerator
      def initialize
        @spec_dir = File.expand_path('../../../spec/cdek_api_client/api/generated', __dir__)
      end

      def generate_all
        FileUtils.mkdir_p(@spec_dir)

        schemas = SchemaLoader.load_schemas['schemas']
        endpoints_by_tag = Hash.new { |h, k| h[k] = [] }

        schemas.each do |schema_entry|
          schema = schema_entry['schema']
          next unless schema['paths']

          schema['paths'].each do |path, methods|
            methods.each do |method, details|
              next unless %w[get post put delete patch].include?(method)

              tag = (details['tags'] || ['Common']).first

              endpoints_by_tag[tag] << {
                path: path,
                method: method,
                operationId: details['operationId'],
                summary: details['summary']
              }
            end
          end
        end

        endpoints_by_tag.each do |tag, endpoints|
          generate_spec_file(tag, endpoints)
        end

        puts "Generated #{endpoints_by_tag.keys.size} RSpec contract test files!"
      end

      private

      def generate_spec_file(tag, endpoints)
        class_name = to_camel_case(tag.gsub(/[^a-zA-Z0-9]/, ''))
        file_name = to_snake_case(class_name)
        file_path = File.join(@spec_dir, "#{file_name}_spec.rb")

        template = <<~ERB
          # frozen_string_literal: true

          # Auto-generated by RspecGenerator
          # This file contains auto-generated contract tests for <%= class_name %>.

          require 'spec_helper'
          require 'testing/auto_mocker'

          RSpec.describe CDEKApiClient::API::<%= class_name %> do
            let(:client) { CDEKApiClient.client }
            let(:api) { described_class.new(client) }
          #{'  '}
            before do
              CDEKApiClient.configure do |config|
                config.client_id = 'test_id'
                config.client_secret = 'test_secret'
              end
              CDEKApiClient::Testing::AutoMocker.stub_all_endpoints!
            end
          #{'  '}
            <% endpoints.each do |ep| %>
            <%#{' '}
              method_name = get_method_name(ep)
              takes_body = %w[post put patch].include?(ep[:method])
              path_params = ep[:path].scan(/\\{([^}]+)\\}/).flatten.map { |p| to_snake_case(p) }
              args = path_params.map { |p| p.include?('uuid') ? "'12345678-1234-5678-9012-123456789abc'" : "'mock_\#{p}'" }
              args << "{}" if takes_body
            %>
            describe '#<%= method_name %>' do
              it 'successfully executes the API call and parses the response without errors' do
                expect {
                  api.<%= method_name %>(<%= args.join(', ') %>)
                }.not_to raise_error
              end
            end
            <% end %>
          end
        ERB

        File.write(file_path, ERB.new(template, trim_mode: '-').result(binding))
      end

      def get_method_name(endpoint)
        EndpointGenerator.method_name_for(endpoint[:operationId], endpoint[:path], endpoint[:method])
      end

      def fallback_method_name(path, _method)
        path.sub(%r{^/?v2/}, '').gsub(/\\{[^}]+\\}/, '').gsub(%r{/+}, '_').chomp('_')
        "\#{method}_\#{clean_path}"
      end

      def to_camel_case(str)
        str.split('_').map(&:capitalize).join
      end

      def to_snake_case(str)
        str.gsub('::', '/')
           .gsub(/([A-Z]+)([A-Z][a-z])/, '\\1_\\2')
           .gsub(/([a-z\\d])([A-Z])/, '\\1_\\2')
           .tr('-', '_')
           .downcase
      end
    end
  end
end
