# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class AuthResponse < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] access_token
      #   @return [String]
      attribute? :access_token, Types::String.optional
      # @!attribute [r] token_type
      #   @return [String]
      attribute? :token_type, Types::String.optional
      # @!attribute [r] expires_in
      #   @return [Integer]
      attribute? :expires_in, Types::Integer.optional
      # @!attribute [r] scope
      #   @return [String]
      attribute? :scope, Types::String.optional
      # @!attribute [r] jti
      #   @return [String]
      attribute? :jti, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
