# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class AuthErrorResponse
      include Validatable

      attr_accessor :alerts

      validates :alerts, type: :array, items: [{ type: :object }]

      # Initializes a new AuthErrorResponse object.
      # @param alerts [Array<Object>]
      def initialize(alerts: nil)
        @alerts = alerts
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          alerts: @alerts
        }.compact.to_json
      end
    end
  end
end
