# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class AuthRequest
      include Validatable

      attr_accessor :request_uuid, :type, :date_time, :state, :errors, :warnings

      validates :request_uuid, type: :string
      validates :type, type: :string, presence: true
      validates :date_time, type: :string, presence: true
      validates :state, type: :string, presence: true
      validates :errors, type: :array, items: [{ type: :object }]
      validates :warnings, type: :array, items: [{ type: :object }]

      # Initializes a new AuthRequest object.
      # @param request_uuid [String]
      # @param type [String]
      # @param date_time [String]
      # @param state [String]
      # @param errors [Array<Object>]
      # @param warnings [Array<Object>]
      def initialize(type:, date_time:, state:, request_uuid: nil, errors: nil, warnings: nil)
        @request_uuid = request_uuid
        @type = type
        @date_time = date_time
        @state = state
        @errors = errors
        @warnings = warnings
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          request_uuid: @request_uuid,
          type: @type,
          date_time: @date_time,
          state: @state,
          errors: @errors,
          warnings: @warnings
        }.compact.to_json
      end
    end
  end
end
