# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class AuthResponse
      include Validatable

      attr_accessor :access_token, :token_type, :expires_in, :scope, :jti

      validates :access_token, type: :string, presence: true
      validates :token_type, type: :string, presence: true
      validates :expires_in, type: :integer, presence: true
      validates :scope, type: :string, presence: true
      validates :jti, type: :string, presence: true

      # Initializes a new AuthResponse object.
      # @param access_token [String]
      # @param token_type [String]
      # @param expires_in [Integer]
      # @param scope [String]
      # @param jti [String]
      def initialize(access_token:, token_type:, expires_in:, scope:, jti:)
        @access_token = access_token
        @token_type = token_type
        @expires_in = expires_in
        @scope = scope
        @jti = jti
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          access_token: @access_token,
          token_type: @token_type,
          expires_in: @expires_in,
          scope: @scope,
          jti: @jti
        }.compact.to_json
      end
    end
  end
end
