# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class CityByCoordinates < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] code
      #   @return [Integer]
      attribute? :code, Types::Integer.optional
      # @!attribute [r] city_uuid
      #   @return [String]
      attribute? :city_uuid, Types::String.optional
      # @!attribute [r] city
      #   @return [String]
      attribute? :city, Types::String.optional
      # @!attribute [r] fias_guid
      #   @return [String]
      attribute? :fias_guid, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
