# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class City < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] code
      #   @return [Integer]
      attribute? :code, Types::Integer.optional
      # @!attribute [r] city_uuid
      #   @return [String]
      attribute? :city_uuid, Types::String.optional
      # @!attribute [r] city
      #   @return [String]
      attribute? :city, Types::String.optional
      # @!attribute [r] fias_guid
      #   @return [String]
      attribute? :fias_guid, Types::String.optional
      # @!attribute [r] country_code
      #   @return [String]
      attribute? :country_code, Types::String.optional
      # @!attribute [r] country
      #   @return [String]
      attribute? :country, Types::String.optional
      # @!attribute [r] region
      #   @return [String]
      attribute? :region, Types::String.optional
      # @!attribute [r] region_code
      #   @return [Integer]
      attribute? :region_code, Types::Integer.optional
      # @!attribute [r] fias_region_guid
      #   @return [String]
      attribute? :fias_region_guid, Types::String.optional
      # @!attribute [r] sub_region
      #   @return [String]
      attribute? :sub_region, Types::String.optional
      # @!attribute [r] longitude
      #   @return [Float, Integer]
      attribute? :longitude, (Types::Float | Types::Integer).optional
      # @!attribute [r] latitude
      #   @return [Float, Integer]
      attribute? :latitude, (Types::Float | Types::Integer).optional
      # @!attribute [r] time_zone
      #   @return [String]
      attribute? :time_zone, Types::String.optional
      # @!attribute [r] payment_limit
      #   @return [Float, Integer]
      attribute? :payment_limit, (Types::Float | Types::Integer).optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
