# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class IntakeInfoResponse < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] uuid
      #   @return [String]
      attribute? :uuid, Types::String.optional
      # @!attribute [r] cdek_number
      #   @return [String]
      attribute? :cdek_number, Types::String.optional
      # @!attribute [r] order_uuid
      #   @return [String]
      attribute? :order_uuid, Types::String.optional
      # @!attribute [r] intake_date
      #   @return [String]
      attribute? :intake_date, Types::String.optional
      # @!attribute [r] intake_number
      #   @return [String]
      attribute? :intake_number, Types::String.optional
      # @!attribute [r] intake_time_from
      #   @return [String]
      attribute? :intake_time_from, Types::String.optional
      # @!attribute [r] intake_time_to
      #   @return [String]
      attribute? :intake_time_to, Types::String.optional
      # @!attribute [r] lunch_time_from
      #   @return [String]
      attribute? :lunch_time_from, Types::String.optional
      # @!attribute [r] lunch_time_to
      #   @return [String]
      attribute? :lunch_time_to, Types::String.optional
      # @!attribute [r] name
      #   @return [String]
      attribute? :name, Types::String.optional
      # @!attribute [r] weight
      #   @return [Integer]
      attribute? :weight, Types::Integer.optional
      # @!attribute [r] length
      #   @return [Integer]
      attribute? :length, Types::Integer.optional
      # @!attribute [r] width
      #   @return [Integer]
      attribute? :width, Types::Integer.optional
      # @!attribute [r] height
      #   @return [Integer]
      attribute? :height, Types::Integer.optional
      # @!attribute [r] comment
      #   @return [String]
      attribute? :comment, Types::String.optional
      # @!attribute [r] courier_power_of_attorney
      #   @return [Boolean]
      attribute? :courier_power_of_attorney, Types::Bool.optional
      # @!attribute [r] courier_identity_card
      #   @return [Boolean]
      attribute? :courier_identity_card, Types::Bool.optional
      # @!attribute [r] sender
      #   @return [Object]
      attribute? :sender, Types::Any.optional
      # @!attribute [r] from_location
      #   @return [Object]
      attribute? :from_location, Types::Any.optional
      # @!attribute [r] to_location
      #   @return [Object]
      attribute? :to_location, Types::Any.optional
      # @!attribute [r] need_call
      #   @return [Boolean]
      attribute? :need_call, Types::Bool.optional
      # @!attribute [r] statuses
      #   @return [Array<Hash>]
      attribute? :statuses, Types::Array.of(Types::Hash).optional
      # @!attribute [r] packages
      #   @return [Array<Hash>]
      attribute? :packages, Types::Array.of(Types::Hash).optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
