# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'
require_relative 'intake_info_response'
require_relative 'auth_request'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class IntakeInfo < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] entity
      #   @return [Object]
      attribute? :entity, IntakeInfoResponse.optional
      # @!attribute [r] requests
      #   @return [Array<AuthRequest>]
      attribute? :requests, Types::Array.of(AuthRequest).optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
