# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class IntakeAvailableDaysRequest < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] from_location
      #   @return [Object]
      attribute? :from_location, Types::Any.optional
      # @!attribute [r] date
      #   @return [String]
      attribute? :date, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
