# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class IntakeAvailableDaysRequest
      include Validatable

      attr_accessor :from_location, :date

      validates :from_location, type: :object, presence: true
      validates :date, type: :string

      # Initializes a new IntakeAvailableDaysRequest object.
      # @param from_location [Object]
      # @param date [String]
      def initialize(from_location:, date: nil)
        @from_location = from_location
        @date = date
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          from_location: @from_location,
          date: @date
        }.compact.to_json
      end
    end
  end
end
