# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class IntakeAvailableDaysResponse
      include Validatable

      attr_accessor :date, :all_days, :errors, :warnings

      validates :date, type: :array, items: [{ type: :string }]
      validates :all_days, type: :boolean
      validates :errors, type: :array, items: [{ type: :object }]
      validates :warnings, type: :array, items: [{ type: :object }]

      # Initializes a new IntakeAvailableDaysResponse object.
      # @param date [Array]
      # @param all_days [Boolean]
      # @param errors [Array<Object>]
      # @param warnings [Array<Object>]
      def initialize(date: nil, all_days: nil, errors: nil, warnings: nil)
        @date = date
        @all_days = all_days
        @errors = errors
        @warnings = warnings
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          date: @date,
          all_days: @all_days,
          errors: @errors,
          warnings: @warnings
        }.compact.to_json
      end
    end
  end
end
