# frozen_string_literal: true

require_relative 'validatable'
require_relative 'payment'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Item
      include Validatable

      attr_accessor :name, :ware_key, :marking, :payment, :weight, :weight_gross, :amount, :name_i18n, :brand, :country_code, :material, :wifi_gsm,
                    :url, :seller, :cost, :feacn_code, :jewel_uin, :used

      validates :name, type: :string, presence: true
      validates :ware_key, type: :string, presence: true
      validates :marking, type: :string
      validates :payment, type: :object, presence: true
      validates :weight, type: :integer, presence: true
      validates :weight_gross, type: :integer
      validates :amount, type: :integer, presence: true
      validates :name_i18n, type: :string
      validates :brand, type: :string
      validates :country_code, type: :string
      validates :material, type: :string
      validates :wifi_gsm, type: :boolean
      validates :url, type: :string
      validates :seller, type: :object
      validates :cost, type: :integer, presence: true
      validates :feacn_code, type: :string
      validates :jewel_uin, type: :string
      validates :used, type: :boolean

      # Initializes a new Item object.
      # @param name [String]
      # @param ware_key [String]
      # @param marking [String]
      # @param payment [Payment]
      # @param weight [Integer]
      # @param weight_gross [Integer]
      # @param amount [Integer]
      # @param name_i18n [String]
      # @param brand [String]
      # @param country_code [String]
      # @param material [String]
      # @param wifi_gsm [Boolean]
      # @param url [String]
      # @param seller [Object]
      # @param cost [Integer]
      # @param feacn_code [String]
      # @param jewel_uin [String]
      # @param used [Boolean]
      def initialize(name:, ware_key:, payment:, weight:, amount:, cost:, marking: nil, weight_gross: nil, name_i18n: nil, brand: nil,
                     country_code: nil, material: nil, wifi_gsm: nil, url: nil, seller: nil, feacn_code: nil, jewel_uin: nil, used: nil)
        @name = name
        @ware_key = ware_key
        @marking = marking
        @payment = payment
        @weight = weight
        @weight_gross = weight_gross
        @amount = amount
        @name_i18n = name_i18n
        @brand = brand
        @country_code = country_code
        @material = material
        @wifi_gsm = wifi_gsm
        @url = url
        @seller = seller
        @cost = cost
        @feacn_code = feacn_code
        @jewel_uin = jewel_uin
        @used = used
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          name: @name,
          ware_key: @ware_key,
          marking: @marking,
          payment: @payment,
          weight: @weight,
          weight_gross: @weight_gross,
          amount: @amount,
          name_i18n: @name_i18n,
          brand: @brand,
          country_code: @country_code,
          material: @material,
          wifi_gsm: @wifi_gsm,
          url: @url,
          seller: @seller,
          cost: @cost,
          feacn_code: @feacn_code,
          jewel_uin: @jewel_uin,
          used: @used
        }.compact.to_json
      end
    end
  end
end
