# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'
require_relative 'payment'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Item < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] name
      #   @return [String]
      attribute? :name, Types::String.optional
      # @!attribute [r] ware_key
      #   @return [String]
      attribute? :ware_key, Types::String.optional
      # @!attribute [r] marking
      #   @return [String]
      attribute? :marking, Types::String.optional
      # @!attribute [r] payment
      #   @return [Object]
      attribute? :payment, Payment.optional
      # @!attribute [r] weight
      #   @return [Integer]
      attribute? :weight, Types::Integer.optional
      # @!attribute [r] weight_gross
      #   @return [Integer]
      attribute? :weight_gross, Types::Integer.optional
      # @!attribute [r] amount
      #   @return [Integer]
      attribute? :amount, Types::Integer.optional
      # @!attribute [r] name_i18n
      #   @return [String]
      attribute? :name_i18n, Types::String.optional
      # @!attribute [r] brand
      #   @return [String]
      attribute? :brand, Types::String.optional
      # @!attribute [r] country_code
      #   @return [String]
      attribute? :country_code, Types::String.optional
      # @!attribute [r] material
      #   @return [String]
      attribute? :material, Types::String.optional
      # @!attribute [r] wifi_gsm
      #   @return [Boolean]
      attribute? :wifi_gsm, Types::Bool.optional
      # @!attribute [r] url
      #   @return [String]
      attribute? :url, Types::String.optional
      # @!attribute [r] seller
      #   @return [Object]
      attribute? :seller, Types::Any.optional
      # @!attribute [r] cost
      #   @return [Float, Integer]
      attribute? :cost, (Types::Float | Types::Integer).optional
      # @!attribute [r] feacn_code
      #   @return [String]
      attribute? :feacn_code, Types::String.optional
      # @!attribute [r] jewel_uin
      #   @return [String]
      attribute? :jewel_uin, Types::String.optional
      # @!attribute [r] used
      #   @return [Boolean]
      attribute? :used, Types::Bool.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
