# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Location
      include Validatable

      attr_accessor :code, :city_uuid, :city, :fias_guid, :kladr_code, :country_code, :country, :region, :region_code, :fias_region_guid,
                    :kladr_region_code, :sub_region, :longitude, :latitude, :time_zone, :payment_limit, :address, :postal_code

      validates :code, type: :integer
      validates :city_uuid, type: :string
      validates :city, type: :string
      validates :fias_guid, type: :string
      validates :kladr_code, type: :string
      validates :country_code, type: :string
      validates :country, type: :string
      validates :region, type: :string
      validates :region_code, type: :integer
      validates :fias_region_guid, type: :string
      validates :kladr_region_code, type: :string
      validates :sub_region, type: :string
      validates :longitude, type: :integer
      validates :latitude, type: :integer
      validates :time_zone, type: :string
      validates :payment_limit, type: :integer
      validates :address, type: :string
      validates :postal_code, type: :string

      # Initializes a new Location object.
      # @param code [Integer]
      # @param city_uuid [String]
      # @param city [String]
      # @param fias_guid [String]
      # @param kladr_code [String]
      # @param country_code [String]
      # @param country [String]
      # @param region [String]
      # @param region_code [Integer]
      # @param fias_region_guid [String]
      # @param kladr_region_code [String]
      # @param sub_region [String]
      # @param longitude [Integer]
      # @param latitude [Integer]
      # @param time_zone [String]
      # @param payment_limit [Integer]
      # @param address [String]
      # @param postal_code [String]
      def initialize(code: nil, city_uuid: nil, city: nil, fias_guid: nil, kladr_code: nil, country_code: nil, country: nil, region: nil,
                     region_code: nil, fias_region_guid: nil, kladr_region_code: nil, sub_region: nil, longitude: nil, latitude: nil, time_zone: nil, payment_limit: nil, address: nil, postal_code: nil)
        @code = code
        @city_uuid = city_uuid
        @city = city
        @fias_guid = fias_guid
        @kladr_code = kladr_code
        @country_code = country_code
        @country = country
        @region = region
        @region_code = region_code
        @fias_region_guid = fias_region_guid
        @kladr_region_code = kladr_region_code
        @sub_region = sub_region
        @longitude = longitude
        @latitude = latitude
        @time_zone = time_zone
        @payment_limit = payment_limit
        @address = address
        @postal_code = postal_code
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          code: @code,
          city_uuid: @city_uuid,
          city: @city,
          fias_guid: @fias_guid,
          kladr_code: @kladr_code,
          country_code: @country_code,
          country: @country,
          region: @region,
          region_code: @region_code,
          fias_region_guid: @fias_region_guid,
          kladr_region_code: @kladr_region_code,
          sub_region: @sub_region,
          longitude: @longitude,
          latitude: @latitude,
          time_zone: @time_zone,
          payment_limit: @payment_limit,
          address: @address,
          postal_code: @postal_code
        }.compact.to_json
      end
    end
  end
end
