# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Location < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] code
      #   @return [Integer]
      attribute? :code, Types::Integer.optional
      # @!attribute [r] postal_code
      #   @return [String]
      attribute? :postal_code, Types::String.optional
      # @!attribute [r] country_code
      #   @return [String]
      attribute? :country_code, Types::String.optional
      # @!attribute [r] city
      #   @return [String]
      attribute? :city, Types::String.optional
      # @!attribute [r] address
      #   @return [String]
      attribute? :address, Types::String.optional
      # @!attribute [r] contragent_type
      #   @return [String]
      attribute? :contragent_type, Types::String.optional
      # @!attribute [r] longitude
      #   @return [Float, Integer]
      attribute? :longitude, (Types::Float | Types::Integer).optional
      # @!attribute [r] latitude
      #   @return [Float, Integer]
      attribute? :latitude, (Types::Float | Types::Integer).optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
