# frozen_string_literal: true

require_relative 'validatable'
require_relative 'sender'
require_relative 'recipient'
require_relative 'service'
require_relative 'package'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class OrderData
      include Validatable

      attr_accessor :type, :additional_order_types, :number, :accompanying_number, :tariff_code, :comment, :shipment_point, :delivery_point,
                    :date_invoice, :shipper_name, :shipper_address, :delivery_recipient_cost, :delivery_recipient_cost_adv, :sender, :seller, :recipient, :from_location, :to_location, :services, :packages, :is_client_return, :has_reverse_order, :developer_key, :print, :widget_token

      validates :type, type: :integer
      validates :additional_order_types, type: :array, items: [{ type: :integer }]
      validates :number, type: :string
      validates :accompanying_number, type: :string
      validates :tariff_code, type: :integer, presence: true
      validates :comment, type: :string
      validates :shipment_point, type: :string
      validates :delivery_point, type: :string
      validates :date_invoice, type: :string
      validates :shipper_name, type: :string
      validates :shipper_address, type: :string
      validates :delivery_recipient_cost, type: :object
      validates :delivery_recipient_cost_adv, type: :array, items: [{ type: :object }]
      validates :sender, type: :object
      validates :seller, type: :object
      validates :recipient, type: :object, presence: true
      validates :from_location, type: :object
      validates :to_location, type: :object
      validates :services, type: :array, items: [Service]
      validates :packages, type: :array, presence: true, items: [Package]
      validates :is_client_return, type: :boolean
      validates :has_reverse_order, type: :boolean
      validates :developer_key, type: :string
      validates :print, type: :string
      validates :widget_token, type: :string

      # Initializes a new OrderData object.
      # @param type [Integer]
      # @param additional_order_types [Array]
      # @param number [String]
      # @param accompanying_number [String]
      # @param tariff_code [Integer]
      # @param comment [String]
      # @param shipment_point [String]
      # @param delivery_point [String]
      # @param date_invoice [String]
      # @param shipper_name [String]
      # @param shipper_address [String]
      # @param delivery_recipient_cost [Object]
      # @param delivery_recipient_cost_adv [Array<Object>]
      # @param sender [Sender]
      # @param seller [Object]
      # @param recipient [Recipient]
      # @param from_location [Object]
      # @param to_location [Object]
      # @param services [Array<Service>]
      # @param packages [Array<Package>]
      # @param is_client_return [Boolean]
      # @param has_reverse_order [Boolean]
      # @param developer_key [String]
      # @param print [String]
      # @param widget_token [String]
      def initialize(tariff_code:, recipient:, packages:, type: nil, additional_order_types: nil, number: nil, accompanying_number: nil,
                     comment: nil, shipment_point: nil, delivery_point: nil, date_invoice: nil, shipper_name: nil, shipper_address: nil, delivery_recipient_cost: nil, delivery_recipient_cost_adv: nil, sender: nil, seller: nil, from_location: nil, to_location: nil, services: nil, is_client_return: nil, has_reverse_order: nil, developer_key: nil, print: nil, widget_token: nil)
        @type = type
        @additional_order_types = additional_order_types
        @number = number
        @accompanying_number = accompanying_number
        @tariff_code = tariff_code
        @comment = comment
        @shipment_point = shipment_point
        @delivery_point = delivery_point
        @date_invoice = date_invoice
        @shipper_name = shipper_name
        @shipper_address = shipper_address
        @delivery_recipient_cost = delivery_recipient_cost
        @delivery_recipient_cost_adv = delivery_recipient_cost_adv
        @sender = sender
        @seller = seller
        @recipient = recipient
        @from_location = from_location
        @to_location = to_location
        @services = services
        @packages = packages
        @is_client_return = is_client_return
        @has_reverse_order = has_reverse_order
        @developer_key = developer_key
        @print = print
        @widget_token = widget_token
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          type: @type,
          additional_order_types: @additional_order_types,
          number: @number,
          accompanying_number: @accompanying_number,
          tariff_code: @tariff_code,
          comment: @comment,
          shipment_point: @shipment_point,
          delivery_point: @delivery_point,
          date_invoice: @date_invoice,
          shipper_name: @shipper_name,
          shipper_address: @shipper_address,
          delivery_recipient_cost: @delivery_recipient_cost,
          delivery_recipient_cost_adv: @delivery_recipient_cost_adv,
          sender: @sender,
          seller: @seller,
          recipient: @recipient,
          from_location: @from_location,
          to_location: @to_location,
          services: @services,
          packages: @packages,
          is_client_return: @is_client_return,
          has_reverse_order: @has_reverse_order,
          developer_key: @developer_key,
          print: @print,
          widget_token: @widget_token
        }.compact.to_json
      end
    end
  end
end
