# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Package < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] weight
      #   @return [Integer]
      attribute? :weight, Types::Integer.optional
      # @!attribute [r] length
      #   @return [Integer]
      attribute? :length, Types::Integer.optional
      # @!attribute [r] width
      #   @return [Integer]
      attribute? :width, Types::Integer.optional
      # @!attribute [r] height
      #   @return [Integer]
      attribute? :height, Types::Integer.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
