# frozen_string_literal: true

require_relative 'validatable'
require_relative 'item'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Package
      include Validatable

      attr_accessor :number, :weight, :length, :width, :height, :comment, :items, :package_id

      validates :number, type: :string, presence: true
      validates :weight, type: :integer, presence: true
      validates :length, type: :integer
      validates :width, type: :integer
      validates :height, type: :integer
      validates :comment, type: :string
      validates :items, type: :array, items: [Item]
      validates :package_id, type: :string

      # Initializes a new Package object.
      # @param number [String]
      # @param weight [Integer]
      # @param length [Integer]
      # @param width [Integer]
      # @param height [Integer]
      # @param comment [String]
      # @param items [Array<Item>]
      # @param package_id [String]
      def initialize(number:, weight:, length: nil, width: nil, height: nil, comment: nil, items: nil, package_id: nil)
        @number = number
        @weight = weight
        @length = length
        @width = width
        @height = height
        @comment = comment
        @items = items
        @package_id = package_id
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          number: @number,
          weight: @weight,
          length: @length,
          width: @width,
          height: @height,
          comment: @comment,
          items: @items,
          package_id: @package_id
        }.compact.to_json
      end
    end
  end
end
