# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class PassportResponse < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] orders
      #   @return [Array<Hash>]
      attribute? :orders, Types::Array.of(Types::Hash).optional
      # @!attribute [r] errors
      #   @return [Array<Hash>]
      attribute? :errors, Types::Array.of(Types::Hash).optional
      # @!attribute [r] warnings
      #   @return [Array<Hash>]
      attribute? :warnings, Types::Array.of(Types::Hash).optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
