# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Payment < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] value
      #   @return [Float, Integer]
      attribute? :value, (Types::Float | Types::Integer).optional
      # @!attribute [r] vat_sum
      #   @return [Float, Integer]
      attribute? :vat_sum, (Types::Float | Types::Integer).optional
      # @!attribute [r] vat_rate
      #   @return [Integer]
      attribute? :vat_rate, Types::Integer.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
