# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Payment
      include Validatable

      attr_accessor :value, :vat_sum, :vat_rate

      validates :value, type: :integer, presence: true
      validates :vat_sum, type: :integer
      validates :vat_rate, type: :integer

      # Initializes a new Payment object.
      # @param value [Integer]
      # @param vat_sum [Integer]
      # @param vat_rate [Integer]
      def initialize(value:, vat_sum: nil, vat_rate: nil)
        @value = value
        @vat_sum = vat_sum
        @vat_rate = vat_rate
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          value: @value,
          vat_sum: @vat_sum,
          vat_rate: @vat_rate
        }.compact.to_json
      end
    end
  end
end
