# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Recipient
      include Validatable

      attr_accessor :company, :name, :contragent_type, :passport_series, :passport_number, :passport_date_of_issue, :passport_organization, :tin,
                    :passport_date_of_birth, :email, :phones, :passport_requirements_satisfied

      validates :company, type: :string
      validates :name, type: :string, presence: true
      validates :contragent_type, type: :string
      validates :passport_series, type: :string
      validates :passport_number, type: :string
      validates :passport_date_of_issue, type: :string
      validates :passport_organization, type: :string
      validates :tin, type: :string
      validates :passport_date_of_birth, type: :string
      validates :email, type: :string
      validates :phones, type: :array, items: [{ type: :object }]
      validates :passport_requirements_satisfied, type: :boolean

      # Initializes a new Recipient object.
      # @param company [String]
      # @param name [String]
      # @param contragent_type [String]
      # @param passport_series [String]
      # @param passport_number [String]
      # @param passport_date_of_issue [String]
      # @param passport_organization [String]
      # @param tin [String]
      # @param passport_date_of_birth [String]
      # @param email [String]
      # @param phones [Array<Object>]
      # @param passport_requirements_satisfied [Boolean]
      def initialize(name:, company: nil, contragent_type: nil, passport_series: nil, passport_number: nil, passport_date_of_issue: nil,
                     passport_organization: nil, tin: nil, passport_date_of_birth: nil, email: nil, phones: nil, passport_requirements_satisfied: nil)
        @company = company
        @name = name
        @contragent_type = contragent_type
        @passport_series = passport_series
        @passport_number = passport_number
        @passport_date_of_issue = passport_date_of_issue
        @passport_organization = passport_organization
        @tin = tin
        @passport_date_of_birth = passport_date_of_birth
        @email = email
        @phones = phones
        @passport_requirements_satisfied = passport_requirements_satisfied
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          company: @company,
          name: @name,
          contragent_type: @contragent_type,
          passport_series: @passport_series,
          passport_number: @passport_number,
          passport_date_of_issue: @passport_date_of_issue,
          passport_organization: @passport_organization,
          tin: @tin,
          passport_date_of_birth: @passport_date_of_birth,
          email: @email,
          phones: @phones,
          passport_requirements_satisfied: @passport_requirements_satisfied
        }.compact.to_json
      end
    end
  end
end
