# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class RegionsResponse < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] country_code
      #   @return [String]
      attribute? :country_code, Types::String.optional
      # @!attribute [r] country
      #   @return [String]
      attribute? :country, Types::String.optional
      # @!attribute [r] region
      #   @return [String]
      attribute? :region, Types::String.optional
      # @!attribute [r] region_code
      #   @return [Integer]
      attribute? :region_code, Types::Integer.optional
      # @!attribute [r] fias_region_guid
      #   @return [String]
      attribute? :fias_region_guid, Types::String.optional
      # @!attribute [r] kladr_region_code
      #   @return [String]
      attribute? :kladr_region_code, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
