# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Sender < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] company
      #   @return [String]
      attribute? :company, Types::String.optional
      # @!attribute [r] name
      #   @return [String]
      attribute? :name, Types::String.optional
      # @!attribute [r] contragent_type
      #   @return [String]
      attribute? :contragent_type, Types::String.optional
      # @!attribute [r] passport_series
      #   @return [String]
      attribute? :passport_series, Types::String.optional
      # @!attribute [r] passport_number
      #   @return [String]
      attribute? :passport_number, Types::String.optional
      # @!attribute [r] passport_date_of_issue
      #   @return [String]
      attribute? :passport_date_of_issue, Types::String.optional
      # @!attribute [r] passport_organization
      #   @return [String]
      attribute? :passport_organization, Types::String.optional
      # @!attribute [r] tin
      #   @return [String]
      attribute? :tin, Types::String.optional
      # @!attribute [r] passport_date_of_birth
      #   @return [String]
      attribute? :passport_date_of_birth, Types::String.optional
      # @!attribute [r] email
      #   @return [String]
      attribute? :email, Types::String.optional
      # @!attribute [r] phones
      #   @return [Array<Hash>]
      attribute? :phones, Types::Array.of(Types::Hash).optional
      # @!attribute [r] passport_requirements_satisfied
      #   @return [Boolean]
      attribute? :passport_requirements_satisfied, Types::Bool.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
