# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Service < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] code
      #   @return [String]
      attribute? :code, Types::String.optional
      # @!attribute [r] parameter
      #   @return [String]
      attribute? :parameter, Types::String.optional
      # @!attribute [r] sum
      #   @return [Float, Integer]
      attribute? :sum, (Types::Float | Types::Integer).optional
      # @!attribute [r] total_sum
      #   @return [Float, Integer]
      attribute? :total_sum, (Types::Float | Types::Integer).optional
      # @!attribute [r] discount_percent
      #   @return [Float, Integer]
      attribute? :discount_percent, (Types::Float | Types::Integer).optional
      # @!attribute [r] discount_sum
      #   @return [Float, Integer]
      attribute? :discount_sum, (Types::Float | Types::Integer).optional
      # @!attribute [r] vat_rate
      #   @return [Float, Integer]
      attribute? :vat_rate, (Types::Float | Types::Integer).optional
      # @!attribute [r] vat_sum
      #   @return [Float, Integer]
      attribute? :vat_sum, (Types::Float | Types::Integer).optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
