# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Service
      include Validatable

      attr_accessor :code, :parameter, :sum, :total_sum, :discount_percent, :discount_sum, :vat_rate, :vat_sum

      validates :code, type: :string
      validates :parameter, type: :string
      validates :sum, type: :integer
      validates :total_sum, type: :integer
      validates :discount_percent, type: :integer
      validates :discount_sum, type: :integer
      validates :vat_rate, type: :integer
      validates :vat_sum, type: :integer

      # Initializes a new Service object.
      # @param code [String]
      # @param parameter [String]
      # @param sum [Integer]
      # @param total_sum [Integer]
      # @param discount_percent [Integer]
      # @param discount_sum [Integer]
      # @param vat_rate [Integer]
      # @param vat_sum [Integer]
      def initialize(code: nil, parameter: nil, sum: nil, total_sum: nil, discount_percent: nil, discount_sum: nil, vat_rate: nil, vat_sum: nil)
        @code = code
        @parameter = parameter
        @sum = sum
        @total_sum = total_sum
        @discount_percent = discount_percent
        @discount_sum = discount_sum
        @vat_rate = vat_rate
        @vat_sum = vat_sum
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          code: @code,
          parameter: @parameter,
          sum: @sum,
          total_sum: @total_sum,
          discount_percent: @discount_percent,
          discount_sum: @discount_sum,
          vat_rate: @vat_rate,
          vat_sum: @vat_sum
        }.compact.to_json
      end
    end
  end
end
