# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class SuggestCityResponse < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] city_uuid
      #   @return [String]
      attribute? :city_uuid, Types::String.optional
      # @!attribute [r] code
      #   @return [Integer]
      attribute? :code, Types::Integer.optional
      # @!attribute [r] full_name
      #   @return [String]
      attribute? :full_name, Types::String.optional
      # @!attribute [r] country_code
      #   @return [String]
      attribute? :country_code, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
