# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'
require_relative 'location'
require_relative 'package'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class TariffData < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] date
      #   @return [String]
      attribute? :date, Types::String.optional
      # @!attribute [r] type
      #   @return [Integer]
      attribute? :type, Types::Integer.optional
      # @!attribute [r] currency
      #   @return [Integer]
      attribute? :currency, Types::Integer.optional
      # @!attribute [r] lang
      #   @return [String]
      attribute? :lang, Types::String.optional
      # @!attribute [r] tariff_code
      #   @return [Integer]
      attribute? :tariff_code, Types::Integer.optional
      # @!attribute [r] from_location
      #   @return [Object]
      attribute? :from_location, Location.optional
      # @!attribute [r] to_location
      #   @return [Object]
      attribute? :to_location, Location.optional
      # @!attribute [r] services
      #   @return [Array<Hash>]
      attribute? :services, Types::Array.of(Types::Hash).optional
      # @!attribute [r] packages
      #   @return [Array<Package>]
      attribute? :packages, Types::Array.of(Package).optional
      # @!attribute [r] additional_order_types
      #   @return [Array]
      attribute? :additional_order_types, Types::Array.of(Types::Integer).optional
      # @!attribute [r] shipment_point
      #   @return [String]
      attribute? :shipment_point, Types::String.optional
      # @!attribute [r] delivery_point
      #   @return [String]
      attribute? :delivery_point, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
