# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class TariffData
      include Validatable

      attr_accessor :date, :type, :currency, :lang, :tariff_code, :from_location, :to_location, :services, :packages, :additional_order_types,
                    :shipment_point, :delivery_point

      validates :date, type: :string
      validates :type, type: :integer
      validates :currency, type: :integer
      validates :lang, type: :string
      validates :tariff_code, type: :integer, presence: true
      validates :from_location, type: :object, presence: true
      validates :to_location, type: :object, presence: true
      validates :services, type: :array, items: [{ type: :object }]
      validates :packages, type: :array, presence: true, items: [{ type: :object }]
      validates :additional_order_types, type: :array, items: [{ type: :integer }]
      validates :shipment_point, type: :string
      validates :delivery_point, type: :string

      # Initializes a new TariffData object.
      # @param date [String]
      # @param type [Integer]
      # @param currency [Integer]
      # @param lang [String]
      # @param tariff_code [Integer]
      # @param from_location [Object]
      # @param to_location [Object]
      # @param services [Array<Object>]
      # @param packages [Array<Object>]
      # @param additional_order_types [Array]
      # @param shipment_point [String]
      # @param delivery_point [String]
      def initialize(tariff_code:, from_location:, to_location:, packages:, date: nil, type: nil, currency: nil, lang: nil, services: nil,
                     additional_order_types: nil, shipment_point: nil, delivery_point: nil)
        @date = date
        @type = type
        @currency = currency
        @lang = lang
        @tariff_code = tariff_code
        @from_location = from_location
        @to_location = to_location
        @services = services
        @packages = packages
        @additional_order_types = additional_order_types
        @shipment_point = shipment_point
        @delivery_point = delivery_point
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          date: @date,
          type: @type,
          currency: @currency,
          lang: @lang,
          tariff_code: @tariff_code,
          from_location: @from_location,
          to_location: @to_location,
          services: @services,
          packages: @packages,
          additional_order_types: @additional_order_types,
          shipment_point: @shipment_point,
          delivery_point: @delivery_point
        }.compact.to_json
      end
    end
  end
end
