# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class TariffResponse < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] delivery_sum
      #   @return [Float, Integer]
      attribute? :delivery_sum, (Types::Float | Types::Integer).optional
      # @!attribute [r] period_min
      #   @return [Integer]
      attribute? :period_min, Types::Integer.optional
      # @!attribute [r] period_max
      #   @return [Integer]
      attribute? :period_max, Types::Integer.optional
      # @!attribute [r] calendar_min
      #   @return [Integer]
      attribute? :calendar_min, Types::Integer.optional
      # @!attribute [r] calendar_max
      #   @return [Integer]
      attribute? :calendar_max, Types::Integer.optional
      # @!attribute [r] weight_calc
      #   @return [Integer]
      attribute? :weight_calc, Types::Integer.optional
      # @!attribute [r] services
      #   @return [Array<Hash>]
      attribute? :services, Types::Array.of(Types::Hash).optional
      # @!attribute [r] total_sum
      #   @return [Float, Integer]
      attribute? :total_sum, (Types::Float | Types::Integer).optional
      # @!attribute [r] currency
      #   @return [String]
      attribute? :currency, Types::String.optional
      # @!attribute [r] errors
      #   @return [Array<Hash>]
      attribute? :errors, Types::Array.of(Types::Hash).optional
      # @!attribute [r] warnings
      #   @return [Array<Hash>]
      attribute? :warnings, Types::Array.of(Types::Hash).optional
      # @!attribute [r] delivery_date_range
      #   @return [Object]
      attribute? :delivery_date_range, Types::Any.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
