# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Webhook < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] uuid
      #   @return [String]
      attribute? :uuid, Types::String.optional
      # @!attribute [r] type
      #   @return [String]
      attribute? :type, Types::String.optional
      # @!attribute [r] url
      #   @return [String]
      attribute? :url, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.reject { |_, v| v.nil? }
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
