# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'
require_relative 'webhook'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class WebhookDataResponse < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] entity
      #   @return [Object]
      attribute? :entity, Webhook.optional
      # @!attribute [r] requests
      #   @return [Array<Hash>]
      attribute? :requests, Types::Array.of(Types::Hash).optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
