# frozen_string_literal: true

require_relative 'validatable'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Webhook
      include Validatable

      attr_accessor :uuid, :type, :url

      validates :uuid, type: :string, presence: true
      validates :type, type: :string, presence: true
      validates :url, type: :string, presence: true

      # Initializes a new Webhook object.
      # @param uuid [String]
      # @param type [String]
      # @param url [String]
      def initialize(uuid:, type:, url:)
        @uuid = uuid
        @type = type
        @url = url
        validate!
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        {
          uuid: @uuid,
          type: @type,
          url: @url
        }.compact.to_json
      end
    end
  end
end
